### PR TITLE
Update russia.md 

### PR DESCRIPTION
**Pull request by wipedlifepotato**

### CODE REVIEW

**Comment by wipedlifepotato** [comment]
Try now

ср, 26 апр. 2023 г., 21:27 Ruslan Ilyasovich Gilfanov <
***@***.***>:

**Comment by wipedlifepotato** [comment]
It's not was up some 1 day because I just forget to start Yggrasil. Is ok.
I have contacts on my website. But I have to create service/daemon. Thanks
for your message

ср, 26 апр. 2023 г., 22:02 Aleksandr Aleksandr ***@***.***>:

**Comment by ri-gilfanov** [comment]
@wipedlifepotato, now every few seconds the connection is established and disconnected:
```
Connected outbound TCP: 200:659c:1e4d:d87e:f6c9:f583:afdc:7559@94.180.118.146:7890, source 192.168.10.103:41872
Disconnected outbound TCP: 200:659c:1e4d:d87e:f6c9:f583:afdc:7559@94.180.118.146:7890, source 192.168.10.103:41872; error: read tcp 192.168.10.103:41872->94.180.118.146:7890: i/o timeout
```
Switching to TLS gives the same result:
```
Connected outbound TLS: 200:659c:1e4d:d87e:f6c9:f583:afdc:7559@94.180.118.146:7891, source 192.168.10.103:60548
Disconnected outbound TLS: 200:659c:1e4d:d87e:f6c9:f583:afdc:7559@94.180.118.146:7891, source 192.168.10.103:60548; error: read tcp 192.168.10.103:60548->94.180.118.146:7891: i/o timeout
```
I checked on two of my nodes. It feels like your Yggdrasil is constantly restarting...

**Comment by wipedlifepotato** [comment]
I did disable the firewall. full... I did change windows yggdrasil to
WSL... I did check that port is opened and i also see logs:

23/04/26 23:37:24 Connected outbound TLS:
***@***.***:4708, source
172.29.143.68:37730
2023/04/26 23:37:24 Disconnected outbound TLS:
***@***.***:4708, source
172.29.143.68:37730
2023/04/26 23:37:24 Connected outbound TLS:
***@***.***:7040, source
172.29.143.68:57694
2023/04/26 23:37:24 Disconnected outbound TLS:
***@***.***:7040, source
172.29.143.68:57694
2023/04/26 23:37:24 Connected outbound TLS:
***@***.***:4708, source
172.29.143.68:37736
2023/04/26 23:37:24 Disconnected outbound TLS:
***@***.***:4708, source
172.29.143.68:37736
2023/04/26 23:37:25 Connected outbound TLS:
***@***.***:7040, source
172.29.143.68:57702
2023/04/26 23:37:25 Disconnected outbound TLS:
***@***.***:7040, source
172.29.143.68:57702
2023/04/26 23:37:25 Connected outbound TLS:
***@***.***:7040, source
172.29.143.68:57712
2023/04/26 23:37:25 Disconnected outbound TLS:
***@***.***:7040, source
172.29.143.68:57712
2023/04/26 23:37:25 Connected outbound TLS:
***@***.***:4708, source
172.29.143.68:37740
2023/04/26 23:37:25 Disconnected outbound TLS:
***@***.***:4708, source
172.29.143.68:37740
2023/04/26 23:37:25 Connected outbound TLS:
***@***.***:4708, source
172.29.143.68:37748
2023/04/26 23:37:25 Disconnected outbound TLS:
***@***.***:4708, source
172.29.143.68:37748
2023/04/26 23:37:26 Connected outbound TLS:
***@***.***:7040, source
172.29.143.68:57720
2023/04/26 23:37:26 Disconnected outbound TLS:
***@***.***:7040, source
172.29.143.68:57720
2023/04/26 23:37:26 Connected outbound TLS:
***@***.***:7040, source
172.29.143.68:57726
2023/04/26 23:37:26 Disconnected outbound TLS:
***@***.***:7040, source
172.29.143.68:57726
2023/04/26 23:37:26 Connected outbound TLS:
***@***.***:4708, source
172.29.143.68:37756
2023/04/26 23:37:26 Disconnected outbound TLS:
***@***.***:4708, source
172.29.143.68:37756
2023/04/26 23:37:27 Connected outbound TLS:
***@***.***:4708, source
172.29.143.68:37768
2023/04/26 23:37:27 Disconnected outbound TLS:
***@***.***:4708, source
172.29.143.68:37768
So. check your client?

ср, 26 апр. 2023 г. в 22:38, Ruslan Ilyasovich Gilfanov <
***@***.***>:

**Comment by wipedlifepotato** [comment]
For now on windows I see this -> 2023/04/26 23:39:11 Creating adapter
2023/04/26 23:39:11 Failed to initiate stub device creation:
Is not fixed yet...

ср, 26 апр. 2023 г. в 23:39, Aleksandr Aleksandr ***@***.***>:

**Comment by wipedlifepotato** [comment]
Oh. is outbound. of course. let me check

ср, 26 апр. 2023 г. в 23:40, Aleksandr Aleksandr ***@***.***>:

**Comment by wipedlifepotato** [comment]
try now

**Comment by ri-gilfanov** [comment]
@wipedlifepotato, now I see this error:
```
22:15:19 Link handler tcp://94.180.118.146:7890 error (94.180.118.146:7890): read handshake: read tcp 192.168.10.103:52082->94.180.118.146:7890: read: connection reset by peer
```
In general, I leave configuration as it is. If you figure it out, you will see an inbound TCP connection from `222:5244:edfe:fdf7:d66f:7658:3fdc:6ebb` in the logs. Also using the command `yggdrasilctl getpeers` you can make sure that traffic is being exchanged with this node.

**Comment by wipedlifepotato** [comment]
2023/04/27 00:41:03 Connected inbound TLS:
***@***.***:35386, source
192.168.0.217:7891
?

чт, 27 апр. 2023 г. в 00:29, Ruslan Ilyasovich Gilfanov <
***@***.***>:

**Comment by wipedlifepotato** [comment]
2023/04/27 00:40:39 Connected inbound TCP:
***@***.***:9030, source
192.168.0.217:7890

чт, 27 апр. 2023 г. в 00:42, Aleksandr Aleksandr ***@***.***>:

**Comment by wipedlifepotato** [comment]
извиняюсь что айпишники спалил из логов. ладно уже.
судя по всему. теперь всё работает?

чт, 27 апр. 2023 г. в 00:43, Aleksandr Aleksandr ***@***.***>:

**Comment by wipedlifepotato** [comment]
yggdrasilctl -endpoint=tcp://localhost:9001 getpeers

чт, 27 апр. 2023 г. в 00:47, Aleksandr Aleksandr ***@***.***>:

**Comment by ri-gilfanov** [comment]
@wipedlifepotato, worked. The connection is stable. Traffic goes both ways.

**Pull request merged**
