### PR TITLE
Update russia.md & add I2P node

### PR DESCRIPTION
**Pull request by TomasGlgg**

### CODE REVIEW

**Comment by cathugger** [comment]
Is this v0.4 or v0.3? There's been protocol change so I'm not really sure what I should do here...

**Comment by TomasGlgg** [comment]
@cathugger 
Screenshot_20210708_234411
Screenshot_20210708_234432
v0. 4 of course, you have problems with the connection?

**Comment by TomasGlgg** [comment]
@cathugger oh yes, I forgot to change the i2p port from tcp to tls

**Comment by cathugger** [comment]
why tls for i2p port? isn't i2p already encrypted? also i should probably test if this works.

**Comment by cathugger** [comment]
ill test later maybe wont block this for now.

**Comment by TomasGlgg** [comment]
> why tls for i2p port? isn't i2p already encrypted? also i should probably test if this works.

I also think this is a strange decision.
Screenshot_20210709_201445

**Pull request merged**
