### PR TITLE
Add badge

### PR DESCRIPTION
**Pull request by podivilov**

### CODE REVIEW

**Comment by wfleurant** [comment]
**Medallion / badge**
image


**Repo. of Medium linked by badge URL**
image

**Comment by podivilov** [comment]
Yeah, what's wrong?

**Comment by wfleurant** [comment]
:thinking: :+1:

**Comment by podivilov** [comment]
@wfleurant, what's wrong?

**Comment by wfleurant** [comment]
i dig it @podivilov :+1:

**Comment by akklesed** [comment]
`https://img.shields.io/badge/Powered_by_Medium-555.svg?logo=data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAA4AAAAOCAYAAAAfSC3RAAAACXBIWXMAAC4jAAAuIwF4pT92AAAAIGNIUk0AAHolAACAgwAA+f8AAIDpAAB1MAAA6mAAADqYAAAXb5JfxUYAAAHKSURBVHjavJK9btNwFMWP/06stFLUOorT2FbiKk4NNHSqmvICSLQSvAILlAVGJNSJmZWOvAELQsBC2yQM/UBICGVqShNXxaaxLZymIpbstJeBVFgMDB040l3uPT/dD12OiHAZMVxSDMBdACaArwDu/MN7C0ALwCGAeyCiH/RHPhGViQh/hUZEbszXg9PtfiGis1iyQUSJGMSI6H2sfu553mdeKxRX8nn5dGJyIjsaSQMAIqr3ej1EUfSE5/n7jP0+h21Ze+/evB0wRVVmapsbLBgEVmyf1SiKbuy3WvOu6z7t9/sYDocIgsBu1OvniqJUWKmsR4IglD80GjYRhSMwwXHcC9/3n307OhIcx4Hv+1FtY9NMJJJXS7oesqncFM0YBuc4Xb190F6/aJlMJivXZmdznYO2c2ia2N3ZWfc8t2xcMZiUk4hNiiKTZRna9HTG7HTWANQu4GKxaFTmrtuDn4OXx9+Pn5d0PZeXZaTTaY6lUql9MZOBpmkAh2Xbsh4AOB2xwkK1qlcXq49VVb1ZKBQgiiJ4nm8zAA/Hxsc/ZrOSp6rqfLPZ9MIwXALwCsDrMAxvb29tnSiqsiBJkicIwicAj7j//qu/BgCMz/3oOPduNwAAAABJRU5ErkJggg==`
that's sorta ugly. can this be made smaller? since it's not even inline but embedded into link..
logo looks not too complicated so maybe it could go directly into svg?

**Comment by podivilov** [comment]
@akklesed, no way. Svg is much larger that png base64 encoded. Much larger.

**Comment by akklesed** [comment]
I meant, that if you can host svg on https://img.shields.io/badge/, then maybe you could have it all in there, and make link much shorter.
No, I didn't want you to fully inline it, if we had multiple servers, inlined images would be even worse.

**Comment by podivilov** [comment]
@akklesed, didn't understand you. How can I host svg on https://img.shields.io/badge/? Sounds like a bad idea.

**Comment by akklesed** [comment]
But initial (and current) link is https://img.shields.io/badge/Powered_by_Medium-555.svg, plus PNG image, passed as parameter.
Why can't it be just https://img.shields.io/badge/Powered_by_Medium-555.svg, and then Powered_by_Medium-555.svg would have that image inside?
Would look much shorter, and it would access https://img.shields.io either way.

That was my initial idea, but I actually went to https://shields.io and didn't see any option to do that, duh.
Guess they don't actually allow hosting custom stuff and generate SVGs on the fly..
So yeah I guess this isn't so doable as I've expected.

Maybe we could just add svg to repo and refer to there..
Either way I don't feel strongly about this anymore.
Would be nice to hear @neilalexander's opinion.
BTW, there be more public Medium peers, which would need these badges too?
Because if yes, then that link really should to be much shorter.

**Comment by podivilov** [comment]
@akklesed, fixed in https://github.com/podivilov/public-peers/commit/c2a99f71a85e7029417b10ce5307d80543e36eec

**Comment by akklesed** [comment]
Or, you could just add powered-by-medium.svg to repository (in same folder as is russian.md), and them make link ``. I think that should work.
Sorry for being pedantic about this lol.

**Comment by podivilov** [comment]
@akklesed done.

**Comment by Arceliar** [comment]
Pinging @neilalexander and @cathugger to see if they have any thoughts on this. I'm a little hesitant to start allowing badges, since we'll need to draw the line somewhere on what kind of content we allow in this repo, and "text only" is a much clearer and less arbitrary line than "images must be this size or smaller".

But putting questions of precedent aside, I do have a couple of thoughts about this PR:
1. I think it's a little redundant to have a badge that links to the medium repo, and also start that line of text with a Medium link to the same page. Perhaps the badge is enough on its own? Or maybe there's something more useful to provide as a text link than the same page with the badge?
2. I'm not sure whether I prefer to store the badge in this repo (as the PR currently does) or somewhere outside (maybe a medium repo?). On the one hand, storing it in this repo prevents people from changing logos without approval (it would be annoying if someone replaced the hosted image with one much larger, for example). On the other hand, I worry about this repo becoming cluttered with logos or other files that aren't necessary to provide connection info. Particularly if someone were (hypothetically speaking) upload a logo containing a copyrighted image, and then use that to issue a DMCA takedown of the repo, as a form of attack on the network.

**Pull request closed without merging**
