### PR TITLE
Update united-states.md

### PR DESCRIPTION
**Pull request by 1200bps**
Added my own peering info

### CODE REVIEW

**Comment by neilalexander** [comment]
[Yggdrasil 0.5](https://github.com/yggdrasil-network/yggdrasil-go/releases) is now released, please update your nodes!

**Comment by 1200bps** [comment]
@neilalexander Thanks for the heads-up—I did a distro upgrade a while back and it removed your repo. Upgraded to 0.5.5, should be good to go!

**Comment by 1200bps** [comment]
Thanks for the heads-up—I did a distro upgrade and it removed your repo. Just upgraded to 0.5.5, should be good to go!

**Comment by neilalexander** [comment]
No problem, thanks a lot!

**Pull request merged**
