### PR TITLE
add more Saudi Arabia Yggdrasil peers

### PR DESCRIPTION
**Pull request by xlmnxp**
it uses router48.org address but it located in Saudi Arabia

### CODE REVIEW

**Comment by cathugger** [comment]
Is it the same node, or different? Port change makes me wonder. If it's different, then separate entry would probably be more fitting?

Also, seems like it's tunneled thru route48 node in Italy, so for latency purposes it would probably be more fitting to count it as european node?

I won't make any calls here or merge myself, probably someone like @neilalexander can know better.

**Comment by xlmnxp** [comment]
this is new server, I know what you mean but the latencyaybe will be high for Europe because to tunneled to my server

**Comment by neilalexander** [comment]
The latency isn't ideal either way, regardless of whether you list it as Italy or Saudi Arabia — it will be worse than the other regional nodes in both cases. In which case, let's list it by the jurisdiction of the node itself: Saudi Arabia.

**Comment by xlmnxp** [comment]
@neilalexander I close the PR because of high latency and there other peer in same region

**Pull request closed without merging**
