### PR TITLE
Add Rostov-on-Don peer

### PR DESCRIPTION
**Pull request by really-not-lavacat**

### CODE REVIEW

**Comment by Vort** [comment]
Something is wrong with it:
image

**Comment by really-not-lavacat** [comment]
I guess tool you used is wrong. I did just used the tool you used, and it said that port is closed. Most of servers on check-host.net connected to my node without any problems: https://check-host.net/check-report/1eae05e0k4da
Also, `yggdrasilctl getpeers` says I have 6 connected to me peers.
image

**Comment by Vort** [comment]
I thought this tool was reliable.
Sorry.

**Comment by really-not-lavacat** [comment]
It's okay, we all make mistakes from time to time.

**Comment by Vort** [comment]
New information:
Looks like this tool scanned IPv6 address and this is where problem is: 

image

**Comment by really-not-lavacat** [comment]
Ahhh, sorry, I forgot I have troubles with IPv6. I'm not sure if I can fix that, but I'll try to! Thanks!

**Comment by neilalexander** [comment]
If you can't accept connections over IPv6, you should ideally remove the AAAA record from the DNS name. 

Although it looks like at the moment `vix.duckdns.org` doesn't resolve reliably at all.

**Comment by really-not-lavacat** [comment]
Well, this DDNS domain belongs not to me but my father. He checked out DDNS service on router (which is on OpenWrt), only IPv4 address is synced with DDNS, so IPv6 isn't, it's just some old address in AAAA record. When we tried to go to DuckDNS' page to remove AAAA from domain, we just got timeout from DuckDNS (I got timeout too), also father don't remember password from DuckDNS. I'm afraid I can do nothing with this problem :(

**Pull request merged**
