### PR TITLE
Update russia.md

### PR DESCRIPTION
**Pull request by AleksMU**
added one server in Moscow

### CODE REVIEW

**Comment by cathugger** [comment]
You don't wanna add maintainer info?

**Comment by AleksMU** [comment]
Only if it is necessary. I want to help :)

**Comment by cathugger** [comment]
Well it's fine with me if you don't wanna, though it'd be easier for others to report to you in case node goes down.
Should I merge this now as it is?

**Comment by AleksMU** [comment]
What I should write?:)

P.S. I added monitoring  ip to nagios. :)

**Comment by cathugger** [comment]
I don't know, whatever you want.
People usually write their nickname, optionally with link to email address or personal website.
I guess you can add that in separate pull request if you want to, so I'll merge this now.

**Comment by whoizit** [comment]
formatting error in markdown

**Pull request merged**
