### PR TITLE
Update russia.md

### PR DESCRIPTION
**Pull request by podivilov**

### CODE REVIEW

**Comment by podivilov** [comment]
Do not merge, please. WIP.

**Comment by neilalexander** [comment]
In future please create the PR once you have done making changes, otherwise our email inboxes get spammed with every commit :-)

**Comment by podivilov** [comment]
@neilalexander, ok. AFAIK it's normal to create PR and return to deployment process.

**Comment by podivilov** [comment]
@neilalexander, PR ready to merge. Please review.

**Comment by podivilov** [comment]
@neilalexander

**Pull request merged**
