### PR TITLE
russia.md: link to chats of russian meshnet community

### PR DESCRIPTION
**Pull request by whoizit**

### CODE REVIEW

**Comment by cathugger** [comment]
I'm not native english speaker, but this sentence looks incorrect to me.

>The owner of public peers is recommended to be in touch in the chats of the [Russian meshnet](https://github.com/russian-meshnet/meshnet-chat-agenda/blob/master/README.md#чаты-и-мосты-в-разных-сетях) community.

Owners of public peers are recommended to be in touch with the chats ["chats" still sounds off to me but I'm not sure how to formulate this better] of the Russian meshnet community.

Maybe use something like "communication channels" instead of "chats"?
I have no idea tbh.

About endorsing this, I'm not sure tbh, I guess some collaboration could be useful but then I can't really think of any good scenarios where this would be too useful. I'm neutral regarding this PR, I guess.

**Comment by whoizit** [comment]
I am not a native speaker, so any advice is welcome

**Comment by whoizit** [comment]
This is done to keep the owner in touch. In another case, owner should leave an e-mail or other contact, such as matrix. Otherwise, we will simply send the PR to delete if the peer does not work for a weeks.

**Comment by whoizit** [comment]
In general, general rules should be developed for peer owners. Should leave some contact. We, in the Russian community, have about 450 people and our people suggest that the owners of peers stay in touch in the community chat, and not just leave contact. Because chatting is moving the community forward.

**Comment by neilalexander** [comment]
So overall I'm happy that you may want to keep people in touch, since that helps us to build up some communities. You might want to write something like this:

> Operators of Yggdrasil public peers in Russia should consider joining the [Russian Meshnet](https://github.com/russian-meshnet/meshnet-chat-agenda/blob/master/README.md#чаты-и-мосты-в-разных-сетях) community channels!

**Comment by cathugger** [comment]
@neilalexander's sentence is much better, and I think it should be that way on document

**Pull request merged**
