### PR TITLE
add werwolf publick nodes

### PR DESCRIPTION
**Pull request by 13werwolf13**

### CODE REVIEW

**Comment by cofob** [comment]
peers2
Not working, but I can ping your ips. Maybe firewall or yggdrasil misconfigured?

**Comment by 13werwolf13** [comment]
@cofob Checked with several providers. Everything works. Can you double-check again?

**Comment by cofob** [comment]
> @cofob Checked with several providers. Everything works. Can you double-check again?


Only ekb.itrus.su working.

**Comment by 13werwolf13** [comment]
rechecked a few more times at different intervals, everything works for me.
where do you check it is possible to see the openness of the port? and run curl on port 443. I would like to find out the problem in ygg or in this server in general.

**Comment by cofob** [comment]
> rechecked a few more times at different intervals, everything works for me. where do you check it is possible to see the openness of the port? and run curl on port 443. I would like to find out the problem in ygg or in this server in general.

Screenshot_20211123_233717
Site on port 443 working, and port opened, but I cant connect with Yggdrasil android app, can you try to comnect with this app?

**Comment by 13werwolf13** [comment]
@cofob

**Comment by 13werwolf13** [comment]
@cofob I corrected something, can you double-check?

**Comment by cofob** [comment]
> @cofob I corrected something, can you double-check?

Works! What you changed?

**Comment by 13werwolf13** [comment]
@cofob 

the changes were not made on my server. after carrying out some number of tests, I found out that the problem is on the central cisco network serving the core. unfortunately I have no right to tell you what exactly and why it did not work.

**Pull request merged**
