### PR TITLE
Add high performance baystate nodes

### PR DESCRIPTION
**Pull request by wfleurant**

### CODE REVIEW

**Comment by neilalexander** [comment]
Somerville node appears to no longer be online: https://publicpeers.neilalexander.dev

**Comment by neilalexander** [comment]
Please note that your peers are running an out-of-date version. The v0.4 network has been live for a couple of weeks now and we will soon start to unlist incompatible nodes running v0.3.x.

**Comment by wfleurant** [comment]
I'll be cleaning this up in the next 24h thanks.

**Comment by wfleurant** [comment]
Too much to do in 24hours .. my v3 peers can be removed.

**Pull request merged**
