### PR TITLE
Fix Brazil, São Paulo IPv6 address

### PR DESCRIPTION
**Pull request by yangm97**

### CODE REVIEW

**Comment by neilalexander** [comment]
Please note that your peers are running an out-of-date version. The v0.4 network has been live for a couple of weeks now and we will soon start to unlist incompatible nodes running v0.3.x.

**Comment by yangm97** [comment]
@neilalexander noted! Gonna update it as soon as possible.

**Comment by yangm97** [comment]
@neilalexander seems like I still have a lot of peers connected... should I upgrade still? Or bring up v0.4 side by side, in another port?

**Comment by neilalexander** [comment]
@yangm97 At this point the v0.3 network is legacy so whether you upgrade in-place or run another separate node is up to you. I would probably upgrade in-place because then existing peers will have peers ready when they also upgrade — breaking connectivity might get people to review their config and upgrade faster maybe?

**Comment by yangm97** [comment]
Done.

**Pull request merged**
