### PR TITLE
added tls://london.sabretruth.org:18472 which has permanent IP

### PR DESCRIPTION
**Pull request by vegabook**
Been running this node as test for a while now seems reliable. It's my main peer for a few servers but happy to show it out to others. It's a dedicated dual core VPS with 1Gbps of umetered outbound bandwidth.

### CODE REVIEW

**Comment by Revertron** [comment]
Any chance for you to provide plain TCP variant on the same node?

**Comment by vegabook** [comment]
> Any chance for you to provide plain TCP variant on the same node?
Sure. this is what my listen field looks like right now: `Listen: [ "tls://[::]:18472" ]` so I assume I just make it into this?
```
Listen: [ 
  "tls://[::]:18472" 
  "tcp://[::]:18473"
]
```

If the tcp format is correct I'll go ahead and do that, open 18473, give it a quick test, and then when confirmed working I'll submit a new pull request.

**Comment by Revertron** [comment]
Yes, it is correct! Thanks!

**Comment by vegabook** [comment]
Okay that's done now and is working. Just tested it.

**Pull request merged**
